/**
 * Parity test: the TypeScript journal-compliance check must produce the SAME
 * result as the engine. Golden fixtures are generated by
 * `python tools/export_journal_fixtures.py` (running report.journal_compliance);
 * this runs the TS port over the same inputs and asserts equality.
 *
 * Run: node --test test/journal.test.ts   (Node 24+, native TypeScript)
 */

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";

import { checkJournal } from "../src/lint/journal.ts";
import type { JournalProfile } from "../src/lint/types.ts";

const HERE = import.meta.dirname;
const FIX = join(HERE, "fixtures", "journal");

function readJson(name: string): any {
  return JSON.parse(readFileSync(join(FIX, name), "utf-8"));
}

interface ManifestEntry {
  name: string;
  profile_id?: string;
  profile?: JournalProfile;
}
const manifest: ManifestEntry[] = readJson("manifest.json");

/** Resolve the profile from the bundled asset (by id) or the inline manifest entry —
 *  the same data the shipped plugin uses. */
function resolveProfile(entry: ManifestEntry): JournalProfile {
  if (entry.profile) return entry.profile;
  return JSON.parse(
    readFileSync(join(HERE, "../src/assets/journals", `${entry.profile_id}.json`), "utf-8")
  );
}

for (const entry of manifest) {
  test(`journal parity: ${entry.name}`, () => {
    const text = readFileSync(join(FIX, `${entry.name}.input.md`), "utf-8");
    const expected = readJson(`${entry.name}.expected.json`);
    const actual = checkJournal(text, resolveProfile(entry));

    assert.deepEqual(actual, expected, `journal compliance mismatch for ${entry.name}`);
  });
}
