/**
 * Parity test: the TypeScript transliteration linter must produce the SAME
 * findings as the Python engine. Golden fixtures are generated by
 * `python tools/export_lint_fixtures.py` (running translit_lint.lint_text);
 * this runs the TS port over the same .md and asserts equality.
 *
 * Run: node --test test/parity.test.ts   (Node 24+, native TypeScript)
 *
 * span_id is excluded from the comparison by design — the engine anchors to
 * span ids, the plugin will anchor to editor ranges (M2); the finding *set*
 * (type, severity, message, fragment, term) and the summary must match exactly.
 */

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";

import { lintText } from "../src/lint/translit.ts";
import { filterTerms } from "../src/lint/types.ts";
import type { Finding, JournalProfile } from "../src/lint/types.ts";

const HERE = import.meta.dirname;
const FIXTURES = join(HERE, "fixtures");

function readJson(name: string): any {
  return JSON.parse(readFileSync(join(FIXTURES, name), "utf-8"));
}

// Use the actual bundled plugin asset (synced from knowledge/) — the same data
// the shipped plugin loads.
const terms = filterTerms(
  JSON.parse(readFileSync(join(HERE, "../src/assets/sanskrit-terms.json"), "utf-8"))
);

interface ManifestEntry {
  name: string;
  profile: JournalProfile | null;
}
const manifest: ManifestEntry[] = readJson("manifest.json");

/** Canonical comparable form of a finding — drops span_id and editor offsets. */
function canon(f: Finding) {
  return {
    type: f.type,
    severity: f.severity,
    message: f.message,
    fragment: f.fragment ?? "",
    term: f.term ?? "",
  };
}

function sortCanon(findings: Finding[]) {
  return findings.map(canon).sort((a, b) => JSON.stringify(a).localeCompare(JSON.stringify(b)));
}

for (const entry of manifest) {
  test(`parity: ${entry.name}`, () => {
    const text = readFileSync(join(FIXTURES, `${entry.name}.md`), "utf-8");
    const expected = readJson(`${entry.name}.expected.json`);
    const actual = lintText(text, terms, entry.profile);

    assert.deepEqual(
      sortCanon(actual.findings),
      sortCanon(expected.findings),
      `findings mismatch for ${entry.name}`
    );
    assert.deepEqual(
      actual.summary,
      expected.summary,
      `summary mismatch for ${entry.name}`
    );
  });
}
