/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD.
RuWritingStyles Obsidian plugin — source lives under src/.
If you want to view the source, visit the plugin's GitHub repository.
*/
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  DEFAULT_SETTINGS: () => DEFAULT_SETTINGS,
  default: () => RuWritingStylesPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");
var import_lint2 = require("@codemirror/lint");

// src/assets/sanskrit-terms.json
var sanskrit_terms_default = [
  { ru: "бхашья", iast: "bhāṣya", source: "Tubb Boose 2007" },
  { ru: "тика", iast: "ṭīkā", source: "Tubb Boose 2007" },
  { ru: "варттика", iast: "vārttika", source: "Tubb Boose 2007" },
  { ru: "вритти", iast: "vṛtti", source: "Tubb Boose 2007" },
  { ru: "сутра", iast: "sūtra", source: "Kochergina 1987" },
  { ru: "шастра", iast: "śāstra", source: "Kochergina 1987" },
  { ru: "шрути", iast: "śruti", source: "Kochergina 1987" },
  { ru: "смрити", iast: "smṛti", source: "Kochergina 1987" },
  { ru: "веда", iast: "veda", source: "Elizarenkova 1982", proper_noun: true, note: "название корпуса текстов; устоявшаяся русская передача (Веды)" },
  { ru: "ригведа", iast: "ṛgveda", source: "Elizarenkova 1982", proper_noun: true, note: "название памятника; устоявшаяся русская передача (Ригведа)" },
  { ru: "атхарваведа", iast: "atharvaveda", source: "Elizarenkova 1982", proper_noun: true, note: "название памятника; устоявшаяся русская передача (Атхарваведа)" },
  { ru: "яджурведа", iast: "yajurveda", source: "Elizarenkova 1982", proper_noun: true, note: "название памятника; устоявшаяся русская передача (Яджурведа)" },
  { ru: "самаведа", iast: "sāmaveda", source: "Elizarenkova 1982", proper_noun: true, note: "название памятника; устоявшаяся русская передача (Самаведа)" },
  { ru: "бхагавадгита", iast: "bhagavadgītā", source: "Smirnov 1962", proper_noun: true, note: "название памятника; устоявшаяся русская передача (Бхагавадгита)" },
  { ru: "упанишада", iast: "upaniṣad", source: "Kochergina 1987" },
  { ru: "брахмана", iast: "brāhmaṇa", source: "Elizarenkova 1982", note: "жанр; не путать с брахман (brahman)" },
  { ru: "араньяка", iast: "āraṇyaka", source: "Kochergina 1987" },
  { ru: "самхита", iast: "saṃhitā", source: "Elizarenkova 1982" },
  { ru: "мантра", iast: "mantra", source: "Elizarenkova 1982" },
  { ru: "шлока", iast: "śloka", source: "Kochergina 1987" },
  { ru: "пада", iast: "pāda", source: "Elizarenkova 1982", note: "стиховая строка/четверть строфы" },
  { ru: "вьякарана", iast: "vyākaraṇa", source: "Tubb Boose 2007" },
  { ru: "дхату", iast: "dhātu", source: "Kochergina 1987" },
  { ru: "пратьяя", iast: "pratyaya", source: "Tubb Boose 2007" },
  { ru: "вибхакти", iast: "vibhakti", source: "Tubb Boose 2007" },
  { ru: "карака", iast: "kāraka", source: "Tubb Boose 2007" },
  { ru: "сандхи", iast: "sandhi", source: "Kochergina 1987" },
  { ru: "гуна", iast: "guṇa", source: "Kochergina 1987" },
  { ru: "вриддхи", iast: "vṛddhi", source: "Kochergina 1987" },
  { ru: "самаса", iast: "samāsa", source: "Tubb Boose 2007" },
  { ru: "татпуруша", iast: "tatpuruṣa", source: "Whitney 1889" },
  { ru: "кармадхарая", iast: "karmadhāraya", source: "Whitney 1889" },
  { ru: "бахуврихи", iast: "bahuvrīhi", source: "Whitney 1889" },
  { ru: "двандва", iast: "dvandva", source: "Whitney 1889" },
  { ru: "двигу", iast: "dvigu", source: "Whitney 1889" },
  { ru: "авьяйибхава", iast: "avyayībhāva", source: "Whitney 1889" },
  { ru: "дхарма", iast: "dharma", source: "Kochergina 1987" },
  { ru: "карма", iast: "karman", source: "Kochergina 1987" },
  { ru: "мокша", iast: "mokṣa", source: "Kochergina 1987" },
  { ru: "атман", iast: "ātman", source: "Kochergina 1987" },
  { ru: "брахман", iast: "brahman", source: "Kochergina 1987", note: "абсолют; не путать с брахмана (brāhmaṇa)" },
  { ru: "пуруша", iast: "puruṣa", source: "Kochergina 1987" },
  { ru: "пракрити", iast: "prakṛti", source: "Kochergina 1987" },
  { ru: "риши", iast: "ṛṣi", source: "Elizarenkova 1993" },
  { ru: "деванагари", iast: "devanāgarī", source: "Kochergina 1987" },
  { ru: "пракрит", iast: "prākṛta", source: "Vertogradova 2002" },
  { ru: "пали", iast: "pāli", source: "Elizarenkova Toporov 1965" },
  { ru: "нирукта", iast: "nirukta", source: "Tubb Boose 2007" },
  { ru: "чхандас", iast: "chandas", source: "Elizarenkova 1982" },
  { ru: "шикша", iast: "śikṣā", source: "Tubb Boose 2007" },
  { ru: "итихаса", iast: "itihāsa", source: "Kochergina 1987" },
  { ru: "пурана", iast: "purāṇa", source: "Kochergina 1987" },
  { ru: "махабхарата", iast: "mahābhārata", source: "Smirnov 1962", proper_noun: true, note: "эпос; имя собственное с устоявшейся русской передачей" },
  { ru: "рамаяна", iast: "rāmāyaṇa", source: "Kochergina 1987", proper_noun: true, note: "эпос; имя собственное с устоявшейся русской передачей" },
  { ru: "кавья", iast: "kāvya", source: "Kochergina 1987" },
  { ru: "аланкара", iast: "alaṃkāra", source: "Tubb Boose 2007" },
  { ru: "раса", iast: "rasa", source: "Kochergina 1987" },
  { ru: "дхвани", iast: "dhvani", source: "Kochergina 1987" },
  { ru: "крит", iast: "kṛt", source: "Tubb Boose 2007", note: "первичный суффикс" },
  { ru: "таддхита", iast: "taddhita", source: "Tubb Boose 2007", note: "вторичный суффикс" },
  { ru: "упасарга", iast: "upasarga", source: "Tubb Boose 2007" },
  { ru: "атманепада", iast: "ātmanepada", source: "Whitney 1889" },
  { ru: "парасмайпада", iast: "parasmaipada", source: "Whitney 1889" },
  { ru: "лакара", iast: "lakāra", source: "Tubb Boose 2007" },
  { ru: "виграха", iast: "vigraha", source: "Tubb Boose 2007", note: "аналитическое разложение сложного слова (самаса)" },
  { ru: "анвая", iast: "anvaya", source: "Tubb Boose 2007", note: "выстраивание слов стиха в прозаический порядок при разборе" },
  { ru: "мула", iast: "mūla", source: "Tubb Boose 2007", note: "коренной текст, к которому пишется комментарий" },
  { ru: "пратипадика", iast: "prātipadika", source: "Kochergina 1987", note: "именная основа до присоединения падежных окончаний" },
  { ru: "кшатрий", iast: "kṣatriya", source: "Kochergina 1987" }
];

// src/assets/journals/vya.json
var vya_default = {
  id: "vya",
  name: "Вопросы языкознания",
  max_chars: 6e4,
  citation_format: "author-year-brackets",
  transliteration_scheme: "IAST",
  first_mention_rule: "ru+iast",
  abstract_required: ["ru", "en"],
  abstract_max_words: 250,
  keywords_required: ["ru", "en"],
  notes: 'Ведущий российский лингвистический журнал (Институт русского языка им. В. В. Виноградова РАН). ИСПРАВЛЕНО 30-07-2026: реальный формат ссылок — НЕ по ГОСТ, а внутритекстовые в квадратных скобках [Иванов 1998: 35] (несколько работ одного автора в один год — буквенный суффикс 1998а/1998б); библиография — алфавитный список "Фамилия год — Фамилия И. О. Название...", источники на нелатинописьменных языках приводятся в латинской транслитерации. Рекомендуемый объём статьи/обзора — 40–60 тыс. знаков с пробелами (рецензии — 20–30 тыс.). Аннотация на РУ и EN — 200–250 слов. Ключевые слова на РУ и EN обязательны, максимум словами в правилах не указан (keywords_max_words не выставлен). Санскритские термины — русская передача с IAST при первом упоминании (внутрипроектная конвенция, не требование журнала). Источник: vja.ruslang.ru/ru/author_guidelines (проверено 30-07-2026).'
};

// src/assets/journals/ppv.json
var ppv_default = {
  id: "ppv",
  name: "Письменные памятники Востока",
  max_chars: 6e4,
  citation_format: "GOST-R-7.0.100-2018",
  transliteration_scheme: "IAST",
  first_mention_rule: "ru+iast",
  abstract_required: ["ru", "en"],
  keywords_required: ["ru", "en"],
  notes: "Востоковедный журнал (ИВР РАН). Допускает развернутый источниковедческий аппарат и более длинные статьи; деванагари и IAST приветствуются при работе с первоисточником."
};

// src/assets/journals/vestnik-spbu.json
var vestnik_spbu_default = {
  id: "vestnik-spbu",
  name: "Вестник СПбГУ. Востоковедение и африканистика",
  max_chars: 4e4,
  citation_format: "GOST-R-7.0.100-2018",
  transliteration_scheme: "IAST",
  first_mention_rule: "ru+iast",
  abstract_required: ["ru", "en"],
  abstract_max_words: 200,
  keywords_required: ["ru", "en"],
  notes: "Университетский востоковедный журнал. Расширенная аннотация (до 200 слов; проверяется через abstract_max_words) и оформление списка литературы по ГОСТ."
};

// src/lint/types.ts
var FINDING_TYPES = [
  "mixed_transliteration_scheme",
  "inconsistent_term_rendering",
  "missing_iast_on_first_mention",
  "devanagari_nfc_issue",
  "iast_in_cyrillic_word"
];
var FINDING_TYPE_LABELS = {
  mixed_transliteration_scheme: "Смешение схем транслитерации (IAST / Harvard-Kyoto)",
  inconsistent_term_rendering: "Непоследовательная передача термина",
  missing_iast_on_first_mention: "Нет IAST при первом упоминании",
  devanagari_nfc_issue: "Деванагари (NFC / OCR)",
  iast_in_cyrillic_word: "Латиница внутри кириллического слова"
};
function filterTerms(raw) {
  return raw.filter((t) => t && typeof t === "object" && t.ru && t.iast);
}

// src/assets.ts
var TERMS = filterTerms(sanskrit_terms_default);
var JOURNALS = {
  vya: vya_default,
  ppv: ppv_default,
  "vestnik-spbu": vestnik_spbu_default
};
var JOURNAL_IDS = ["none", ...Object.keys(JOURNALS)];

// src/lint/segment.ts
var FENCE_RE = /^[ \t]{0,3}(`{3,}|~{3,})/;
var HEADING_RE = /^[ \t]{0,3}#{1,6}(?:\s+|$)/;
var CONTROL_RE = /[\x00-\x08\x0b\x0c\x0e-\x1f]/g;
function normalizeDocument(text, maxBlankLines = 2) {
  let t = text.normalize("NFC");
  t = t.replace(/﻿/g, "");
  t = t.replace(/\r\n/g, "\n").replace(/\r/g, "\n");
  t = t.replace(CONTROL_RE, "");
  t = t.split("\n").map((line) => line.replace(/[ \t]+$/, "")).join("\n");
  if (maxBlankLines >= 0) {
    t = limitBlankLines(t, maxBlankLines);
  }
  return t.replace(/^\s+|\s+$/g, "") + "\n";
}
function limitBlankLines(text, maxBlankLines) {
  const out = [];
  let blank = 0;
  for (const line of text.split("\n")) {
    if (line) {
      blank = 0;
      out.push(line);
      continue;
    }
    blank += 1;
    if (blank <= maxBlankLines) out.push(line);
  }
  return out.join("\n");
}
function splitLines(text) {
  const parts = text.split("\n");
  if (parts.length > 0 && parts[parts.length - 1] === "") parts.pop();
  return parts;
}
function closesFence(candidate, opener) {
  return !!opener && candidate[0] === opener[0] && candidate.length >= opener.length;
}
function segmentMarkdown(text) {
  var _a;
  const lines = splitLines(text);
  const lineOffsets = [];
  let off = 0;
  for (const line of lines) {
    lineOffsets.push(off);
    off += line.length + 1;
  }
  const raw = [];
  let paragraph = [];
  let paragraphStartLine = 0;
  let inFence = false;
  let fenceMarker = "";
  let fence = [];
  let fenceStartLine = 0;
  const flushParagraph = () => {
    var _a2;
    if (paragraph.length === 0) return;
    const content = paragraph.join("\n").replace(/^\s+|\s+$/g, "");
    if (content) {
      raw.push({ type: "paragraph", text: content, offset: (_a2 = lineOffsets[paragraphStartLine]) != null ? _a2 : 0 });
    }
    paragraph = [];
  };
  const flushFence = () => {
    var _a2;
    if (fence.length > 0) {
      raw.push({ type: "code", text: fence.join("\n"), offset: (_a2 = lineOffsets[fenceStartLine]) != null ? _a2 : 0 });
    }
    fence = [];
  };
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const stripped = line.replace(/^\s+|\s+$/g, "");
    const fenceMatch = FENCE_RE.exec(line);
    if (fenceMatch) {
      if (inFence) {
        fence.push(line);
        if (closesFence(fenceMatch[1], fenceMarker)) {
          flushFence();
          inFence = false;
          fenceMarker = "";
        }
      } else {
        flushParagraph();
        inFence = true;
        fenceMarker = fenceMatch[1];
        fenceStartLine = i;
        fence = [line];
      }
      continue;
    }
    if (inFence) {
      fence.push(line);
      continue;
    }
    if (!stripped) {
      flushParagraph();
      continue;
    }
    if (HEADING_RE.test(line)) {
      flushParagraph();
      raw.push({ type: "heading", text: stripped, offset: (_a = lineOffsets[i]) != null ? _a : 0 });
      continue;
    }
    if (stripped.startsWith("<!--") && stripped.includes("rws:")) {
      continue;
    }
    if (paragraph.length === 0) paragraphStartLine = i;
    paragraph.push(line);
  }
  if (inFence) flushFence();
  else flushParagraph();
  const prefix = { heading: "h", paragraph: "p", code: "c" };
  return raw.map((seg, idx) => ({
    span_id: `${prefix[seg.type]}${String(idx + 1).padStart(3, "0")}`,
    text: seg.text,
    start_offset: seg.offset
  }));
}

// src/lint/translit.ts
var IAST_DIACRITICS = new Set(
  "āīūṛṝḷḹṃḥṅñṭḍṇśṣĀĪŪṚṜḶḸṂḤṄÑṬḌṆŚṢ"
);
var DEVANAGARI_RE = /[ऀ-ॿ]/;
var ORPHAN_MATRA_RE = /(?:^|[\s(«"'])[ऺ-्ॢॣ]/;
var WORD_PATTERN = "[\\p{L}\\p{M}]+(?:['’\\-][\\p{L}\\p{M}]+)*";
var WORD_RE = new RegExp(WORD_PATTERN, "gu");
var HK_MARKER_RE = /.[AIURTDNSGJMHLZ]|aa|ii|uu/;
var CYRILLIC_RE = /[Ѐ-ӿ]/;
var LATIN_BASIC_RE = /[a-zA-Z]/;
var SPLIT_TOKEN_RE = /['’\-‐‑‒–]/;
var RU_VOWELS = "аеёиоуыэюя";
var RU_ENDINGS = /* @__PURE__ */ new Set([
  "",
  "а",
  "я",
  "у",
  "ю",
  "е",
  "и",
  "ы",
  "о",
  "ой",
  "ей",
  "ам",
  "ям",
  "ах",
  "ях",
  "ом",
  "ем",
  "ов",
  "ев",
  "ами",
  "ями"
]);
var FINDING_TYPES2 = [
  "mixed_transliteration_scheme",
  "inconsistent_term_rendering",
  "missing_iast_on_first_mention",
  "devanagari_nfc_issue",
  "iast_in_cyrillic_word"
];
function hasCyrillic(word) {
  return CYRILLIC_RE.test(word);
}
function hasLatin(word) {
  if (LATIN_BASIC_RE.test(word)) return true;
  for (const ch of word) if (IAST_DIACRITICS.has(ch)) return true;
  return false;
}
function isIastWord(word) {
  for (const ch of word) if (IAST_DIACRITICS.has(ch)) return true;
  return false;
}
function hasFusedMixedToken(word) {
  for (const token of word.split(SPLIT_TOKEN_RE)) {
    if (token && hasCyrillic(token) && hasLatin(token)) return true;
  }
  return false;
}
function skeleton(word) {
  const decomposed = word.toLowerCase().normalize("NFD");
  let out = "";
  for (const ch of decomposed) if (ch >= "a" && ch <= "z") out += ch;
  return out;
}
function ruStem(ru) {
  const last = ru.slice(-1);
  return ru && (RU_VOWELS.includes(last) || last === "ь") ? ru.slice(0, -1) : ru;
}
function matchesRuTerm(word, termRu) {
  const w = word.toLowerCase();
  const stem = ruStem(termRu.toLowerCase());
  if (!w.startsWith(stem)) return false;
  return RU_ENDINGS.has(w.slice(stem.length));
}
function words(text) {
  var _a;
  return (_a = text.match(WORD_RE)) != null ? _a : [];
}
function finding(spanId, type, message, severity, fragment = "", term = "") {
  const item = { span_id: spanId, type, message, severity };
  if (fragment) item.fragment = fragment;
  if (term) item.term = term;
  return item;
}
function lintSegments(segments, terms, profile) {
  var _a;
  const firstMentionRule = (_a = profile == null ? void 0 : profile.first_mention_rule) != null ? _a : "ru+iast";
  const requireIastFirstMention = firstMentionRule === "ru+iast" || firstMentionRule === "iast+ru";
  const properNouns = new Set(terms.filter((t) => t.proper_noun).map((t) => t.ru));
  const findings = [];
  const iastExamples = [];
  const hkExamples = [];
  const termSkeletons = /* @__PURE__ */ new Map();
  for (const t of terms) termSkeletons.set(skeleton(t.iast), t);
  const ruSeen = /* @__PURE__ */ new Map();
  const ruSeenProse = /* @__PURE__ */ new Map();
  const iastSeen = /* @__PURE__ */ new Map();
  for (const t of terms) {
    ruSeen.set(t.ru, []);
    ruSeenProse.set(t.ru, []);
    iastSeen.set(t.ru, []);
  }
  const firstMentionFlagged = /* @__PURE__ */ new Set();
  const prose = segments.filter((s) => !s.span_id.startsWith("c") && s.text);
  for (const seg of prose) {
    const spanId = seg.span_id;
    const text = seg.text;
    const isHeading = spanId.startsWith("h");
    if (DEVANAGARI_RE.test(text)) {
      if (text !== text.normalize("NFC")) {
        findings.push(
          finding(
            spanId,
            "devanagari_nfc_issue",
            "Деванагари не в форме NFC: возможна потеря огласовок при поиске и сравнении.",
            "error"
          )
        );
      }
      const orphan = ORPHAN_MATRA_RE.exec(text);
      if (orphan) {
        findings.push(
          finding(
            spanId,
            "devanagari_nfc_issue",
            "Огласовка деванагари без опорного согласного (вероятный артефакт OCR).",
            "error",
            orphan[0].trim()
          )
        );
      }
    }
    for (const word of words(text)) {
      const cyr = hasCyrillic(word);
      const lat = hasLatin(word);
      if (cyr && lat && hasFusedMixedToken(word)) {
        findings.push(
          finding(
            spanId,
            "iast_in_cyrillic_word",
            `Смешение кириллицы и латиницы внутри словоформы: «${word}».`,
            "error",
            word
          )
        );
        continue;
      }
      if (lat && isIastWord(word)) {
        iastExamples.push(word);
      } else if (lat && HK_MARKER_RE.test(word)) {
        if (termSkeletons.has(skeleton(word))) hkExamples.push([spanId, word]);
      }
    }
    const lowered = text.toLowerCase();
    const loweredWords = words(lowered);
    for (const term of terms) {
      const ru = term.ru;
      const iast = term.iast.toLowerCase();
      if (lowered.includes(iast)) iastSeen.get(ru).push(spanId);
      const ruHit = loweredWords.some((w) => hasCyrillic(w) && matchesRuTerm(w, ru));
      if (ruHit) {
        ruSeen.get(ru).push(spanId);
        if (isHeading) continue;
        ruSeenProse.get(ru).push(spanId);
        const firstEver = ruSeenProse.get(ru).length === 1 && iastSeen.get(ru).length === 0;
        if (requireIastFirstMention && !properNouns.has(ru) && firstEver && !lowered.includes(iast) && !firstMentionFlagged.has(ru)) {
          firstMentionFlagged.add(ru);
          findings.push(
            finding(
              spanId,
              "missing_iast_on_first_mention",
              `Первое упоминание термина «${ru}» без IAST в скобках: ожидается «${ru} (${term.iast})».`,
              "warning",
              "",
              ru
            )
          );
        }
      }
    }
  }
  if (iastExamples.length > 0 && hkExamples.length > 0) {
    const [spanId, hkWord] = hkExamples[0];
    findings.push(
      finding(
        spanId,
        "mixed_transliteration_scheme",
        `В тексте смешаны схемы транслитерации: IAST (напр., «${iastExamples[0]}») и Harvard-Kyoto (напр., «${hkWord}»). Приведите к одной схеме (для журналов — IAST).`,
        "error",
        hkWord
      )
    );
  }
  for (const term of terms) {
    const ru = term.ru;
    if (properNouns.has(ru)) continue;
    const ruList = ruSeen.get(ru);
    const unpairedIast = iastSeen.get(ru).filter((s) => !ruList.includes(s));
    if (ruList.length >= 2 && unpairedIast.length >= 2) {
      findings.push(
        finding(
          unpairedIast[0],
          "inconsistent_term_rendering",
          `Термин передается то кириллицей («${ru}»), то латиницей («${term.iast}») без системы; выберите основную форму, вторую давайте в скобках при первом упоминании.`,
          "warning",
          "",
          ru
        )
      );
    }
  }
  const findingCounts = {};
  for (const ftype of FINDING_TYPES2) {
    findingCounts[ftype] = findings.filter((f) => f.type === ftype).length;
  }
  const schemes = [
    ...iastExamples.length ? ["iast"] : [],
    ...hkExamples.length ? ["harvard-kyoto"] : []
  ].sort();
  return {
    status: "completed",
    findings,
    summary: {
      segments_checked: prose.length,
      iast_word_count: iastExamples.length,
      hk_word_count: hkExamples.length,
      schemes_detected: schemes,
      finding_counts: findingCounts
    }
  };
}
function lintText(text, terms, profile) {
  var _a, _b, _c, _d;
  const rawNfcIssue = DEVANAGARI_RE.test(text) && text !== text.normalize("NFC");
  const normalized = normalizeDocument(text);
  const segments = segmentMarkdown(normalized);
  const result = lintSegments(segments, terms, profile);
  if (rawNfcIssue) {
    const anchor = (_d = (_c = (_a = segments.find((s) => DEVANAGARI_RE.test(s.text))) == null ? void 0 : _a.span_id) != null ? _c : (_b = segments[0]) == null ? void 0 : _b.span_id) != null ? _d : "p001";
    result.findings.unshift(
      finding(
        anchor,
        "devanagari_nfc_issue",
        "Исходный файл содержит деванагари не в форме NFC: нормализуйте файл (NFC), иначе поиск и сравнение строк ненадежны.",
        "error"
      )
    );
    result.summary.finding_counts.devanagari_nfc_issue += 1;
  }
  return result;
}

// src/lint/locate.ts
function locateFinding(text, finding2, terms) {
  if (finding2.fragment) {
    const idx = text.indexOf(finding2.fragment);
    if (idx >= 0 && finding2.fragment.length > 0) {
      return { from: idx, to: idx + finding2.fragment.length };
    }
    return null;
  }
  if (finding2.type === "missing_iast_on_first_mention" && finding2.term) {
    const re = new RegExp(WORD_PATTERN, "gu");
    let m;
    while ((m = re.exec(text)) !== null) {
      const w = m[0];
      if (hasCyrillic(w) && matchesRuTerm(w, finding2.term)) {
        return { from: m.index, to: m.index + w.length };
      }
    }
    return null;
  }
  if (finding2.type === "inconsistent_term_rendering" && finding2.term) {
    const term = terms.find((t) => t.ru === finding2.term);
    if (term) {
      const idx = text.toLowerCase().indexOf(term.iast.toLowerCase());
      if (idx >= 0) return { from: idx, to: idx + term.iast.length };
    }
    return null;
  }
  return null;
}
function locateFindings(text, findings, terms) {
  return findings.map((f) => {
    const range = locateFinding(text, f, terms);
    return range ? { ...f, from: range.from, to: range.to } : { ...f };
  });
}

// src/lint/journal.ts
var ABSTRACT_MARKERS = {
  ru: ["аннотац", "резюме"],
  en: ["abstract"]
};
var KEYWORDS_MARKERS = {
  ru: ["ключевые слова"],
  en: ["keywords", "key words"]
};
var WORD_RE2 = /[\p{L}\p{N}]+/gu;
var ALPHA_RE = /\p{L}/u;
var ALNUM_RE = /[\p{L}\p{N}]/u;
function abstractWordCount(text, low, markers) {
  var _a;
  let idx = -1;
  let mlen = 0;
  for (const m of markers) {
    const pos = low.indexOf(m);
    if (pos !== -1 && (idx === -1 || pos < idx)) {
      idx = pos;
      mlen = m.length;
    }
  }
  if (idx === -1) return 0;
  const end = text.indexOf("\n\n", idx);
  const block = end === -1 ? text.slice(idx) : text.slice(idx, end);
  let j = mlen;
  while (j < block.length && ALPHA_RE.test(block[j])) j++;
  while (j < block.length && !ALNUM_RE.test(block[j])) j++;
  return ((_a = block.slice(j).match(WORD_RE2)) != null ? _a : []).length;
}
function checkJournal(text, profile) {
  var _a, _b, _c, _d, _e, _f;
  if (!profile || !profile.name) return null;
  const normalized = text.replace(/\r\n/g, "\n");
  const low = normalized.toLowerCase();
  const comp = {
    name: profile.name,
    length: null,
    // null (not undefined) to mirror the engine's JSON shape for absent fields.
    citationFormat: (_a = profile.citation_format) != null ? _a : null,
    transliterationScheme: (_b = profile.transliteration_scheme) != null ? _b : null,
    abstract: [],
    keywords: []
  };
  if (typeof profile.max_chars === "number" && profile.max_chars > 0) {
    const current = [...normalized].length;
    comp.length = {
      current,
      max: profile.max_chars,
      over: Math.max(0, current - profile.max_chars)
    };
  }
  const maxWords = typeof profile.abstract_max_words === "number" && profile.abstract_max_words > 0 ? profile.abstract_max_words : null;
  for (const lang of (_c = profile.abstract_required) != null ? _c : []) {
    const markers = (_d = ABSTRACT_MARKERS[lang]) != null ? _d : [];
    const present = markers.some((m) => low.includes(m));
    const item = { lang, present };
    if (maxWords !== null && present) {
      const words2 = abstractWordCount(normalized, low, markers);
      item.words = words2;
      item.max = maxWords;
      item.over = Math.max(0, words2 - maxWords);
    }
    comp.abstract.push(item);
  }
  const kwMaxWords = typeof profile.keywords_max_words === "number" && profile.keywords_max_words > 0 ? profile.keywords_max_words : null;
  for (const lang of (_e = profile.keywords_required) != null ? _e : []) {
    const markers = (_f = KEYWORDS_MARKERS[lang]) != null ? _f : [];
    const present = markers.some((m) => low.includes(m));
    const item = { lang, present };
    if (kwMaxWords !== null && present) {
      const words2 = abstractWordCount(normalized, low, markers);
      item.words = words2;
      item.max = kwMaxWords;
      item.over = Math.max(0, words2 - kwMaxWords);
    }
    comp.keywords.push(item);
  }
  return comp;
}
function journalGaps(comp) {
  const gaps = [];
  if (comp.length && comp.length.over > 0) {
    gaps.push({
      severity: "warning",
      message: `Объём ${comp.length.current} знаков превышает лимит журнала «${comp.name}» (${comp.length.max}) на ${comp.length.over}.`
    });
  }
  for (const a of comp.abstract) {
    if (!a.present) {
      gaps.push({
        severity: "warning",
        message: `Нет аннотации на языке «${a.lang}» (требует «${comp.name}»).`
      });
    } else if (a.over && a.over > 0) {
      gaps.push({
        severity: "warning",
        message: `Аннотация «${a.lang}» — ${a.words} слов, превышает лимит журнала «${comp.name}» (${a.max}) на ${a.over}.`
      });
    }
  }
  for (const k of comp.keywords) {
    if (!k.present) {
      gaps.push({
        severity: "warning",
        message: `Нет ключевых слов на языке «${k.lang}» (требует «${comp.name}»).`
      });
    } else if (k.over && k.over > 0) {
      gaps.push({
        severity: "warning",
        message: `Ключевые слова «${k.lang}» — ${k.words} слов, превышает лимит журнала «${comp.name}» (${k.max}) на ${k.over}.`
      });
    }
  }
  return gaps;
}
function summarizeJournal(comp) {
  const parts = [];
  if (comp.length) {
    parts.push(
      `объём ${comp.length.current}/${comp.length.max}` + (comp.length.over > 0 ? ` (+${comp.length.over})` : " ✓")
    );
  }
  if (comp.abstract.length) {
    parts.push(
      "аннотация " + comp.abstract.map((a) => {
        const base = `${a.lang} ${a.present ? "✓" : "✗"}`;
        if (a.words === void 0) return base;
        return `${base} (${a.words}/${a.max}${a.over ? ` +${a.over}` : " ✓"})`;
      }).join(" ")
    );
  }
  if (comp.keywords.length) {
    parts.push(
      "ключевые слова " + comp.keywords.map((k) => {
        const base = `${k.lang} ${k.present ? "✓" : "✗"}`;
        if (k.words === void 0) return base;
        return `${base} (${k.words}/${k.max}${k.over ? ` +${k.over}` : " ✓"})`;
      }).join(" ")
    );
  }
  return `${comp.name}: ${parts.join("; ")}`;
}

// src/settings.ts
var import_obsidian = require("obsidian");

// src/tier2/audit-core.ts
var VALID_PROVIDERS = [
  "deepseek",
  "openai",
  "google",
  "anthropic",
  "openrouter",
  "local",
  "ollama",
  "mock"
];
var VALID_PROFILES = ["researcher", "editor", "student"];
var POLL_INTERVAL_MS = 3e3;
var MAX_POLL_ATTEMPTS = 300;
var MAX_CONSECUTIVE_FAILURES = 3;
function executeBody(text, filename, s) {
  if (!VALID_PROVIDERS.includes(s.provider)) {
    throw new ClientConfigError(`unknown provider: ${s.provider}`);
  }
  if (!VALID_PROFILES.includes(s.profile)) {
    throw new ClientConfigError(`unknown profile: ${s.profile}`);
  }
  const body = {
    text,
    filename,
    provider: s.provider,
    profile: s.profile,
    execute: true
  };
  if (s.journal && s.journal !== "none") body.journal = s.journal;
  return body;
}
function auditHeaders(s) {
  const headers = { "Content-Type": "application/json" };
  if (s.apiToken) headers["Authorization"] = `Bearer ${s.apiToken}`;
  return headers;
}
function isTerminal(status) {
  return status === "completed" || status === "failed" || status === "needs_human_review";
}
function validateExecuteResponse(json) {
  if (!json || typeof json !== "object") {
    throw new Error("execute: response is not a JSON object");
  }
  const runId = json.run_id;
  if (typeof runId !== "string" || !runId) {
    throw new Error("execute: response missing run_id");
  }
  return { run_id: runId };
}
function validateRunDetails(json) {
  if (!json || typeof json !== "object") {
    throw new Error("run details: response is not a JSON object");
  }
  const o = json;
  if (o.status !== void 0 && typeof o.status !== "string") {
    throw new Error("run details: status is not a string");
  }
  return o;
}
function warningCount(d) {
  var _a;
  return Array.isArray((_a = d.verification) == null ? void 0 : _a.warnings) ? d.verification.warnings.length : 0;
}
function summarizeRun(d) {
  var _a, _b, _c;
  const decisions = Array.isArray((_a = d.council) == null ? void 0 : _a.decisions) ? d.council.decisions.length : 0;
  const verdict = ((_b = d.verification) == null ? void 0 : _b.passed) === true ? "пройдена" : ((_c = d.verification) == null ? void 0 : _c.status) ? String(d.verification.status) : "—";
  const origLen = d.original_text ? [...d.original_text].length : 0;
  const revLen = d.revised_text ? [...d.revised_text].length : 0;
  return `решений совета: ${decisions}; верификация: ${verdict}; предупреждений: ${warningCount(d)}; объём ${origLen}→${revLen}`;
}
function baseUrl(s) {
  return s.backendUrl.replace(/\/+$/, "");
}
function isValidBackendUrl(url) {
  return /^https?:\/\/.+/.test(url.trim());
}
var RunNotFoundError = class extends Error {
};
var TransientError = class extends Error {
};
var ClientConfigError = class extends Error {
};
function classifyHttpStatus(status) {
  if (status >= 200 && status < 300) return "ok";
  if (status === 404) return "not_found";
  if (status === 429 || status >= 500) return "transient";
  return "client_config";
}
function shouldAbortPolling(args) {
  if (args.fatal === "not_found") return { abort: true, reason: "not_found" };
  if (args.fatal === "client_config") return { abort: true, reason: "client_config" };
  if (isTerminal(args.status)) return { abort: true, reason: "completed" };
  if (args.consecutiveFailures >= MAX_CONSECUTIVE_FAILURES) {
    return { abort: true, reason: "transient_exhausted" };
  }
  if (args.attempt >= MAX_POLL_ATTEMPTS) return { abort: true, reason: "timeout" };
  return { abort: false };
}
function sanitizeRunId(id) {
  return id.replace(/[^A-Za-z0-9._-]/g, "_") || "run";
}
function wsUrl(s, runId) {
  const base = baseUrl(s).replace(/^http/, "ws");
  const query = s.apiToken ? `?token=${encodeURIComponent(s.apiToken)}` : "";
  return `${base}/ws/${encodeURIComponent(runId)}${query}`;
}
function formatTraceMessage(msg) {
  if (!msg || typeof msg !== "object") return null;
  const m = msg;
  const status = typeof m.status === "string" ? m.status : "";
  if (m.type === "step_update") {
    const step = typeof m.step_id === "string" ? m.step_id : "шаг";
    return `${step}: ${status || "…"}`;
  }
  if (m.type === "run_status") return status || null;
  if (typeof m.tool === "string") return `инструмент: ${m.tool}`;
  if (typeof m.message === "string") return m.message;
  return status || null;
}
function splitLines2(text) {
  return text.replace(/\r\n/g, "\n").split("\n");
}
function diffLines(original, revised) {
  const a = splitLines2(original);
  const b = splitLines2(revised);
  const n = a.length;
  const m = b.length;
  const dp = Array.from({ length: n + 1 }, () => new Array(m + 1).fill(0));
  for (let i2 = n - 1; i2 >= 0; i2--) {
    for (let j2 = m - 1; j2 >= 0; j2--) {
      dp[i2][j2] = a[i2] === b[j2] ? dp[i2 + 1][j2 + 1] + 1 : Math.max(dp[i2 + 1][j2], dp[i2][j2 + 1]);
    }
  }
  const hunks = [];
  let eq = [];
  let before = [];
  let after = [];
  const flushEq = () => {
    if (eq.length) {
      hunks.push({ kind: "equal", lines: eq });
      eq = [];
    }
  };
  const flushChange = () => {
    if (before.length || after.length) {
      hunks.push({ kind: "change", before, after });
      before = [];
      after = [];
    }
  };
  let i = 0;
  let j = 0;
  while (i < n && j < m) {
    if (a[i] === b[j]) {
      flushChange();
      eq.push(a[i]);
      i++;
      j++;
    } else if (dp[i + 1][j] >= dp[i][j + 1]) {
      flushEq();
      before.push(a[i]);
      i++;
    } else {
      flushEq();
      after.push(b[j]);
      j++;
    }
  }
  while (i < n) {
    flushEq();
    before.push(a[i]);
    i++;
  }
  while (j < m) {
    flushEq();
    after.push(b[j]);
    j++;
  }
  flushChange();
  flushEq();
  return hunks;
}
function countChangeHunks(hunks) {
  return hunks.filter((h) => h.kind === "change").length;
}
function detectEol(text) {
  return text.includes("\r\n") ? "\r\n" : "\n";
}
function reconstruct(hunks, acceptedChangeIndices, eol = "\n") {
  const out = [];
  let changeIdx = 0;
  for (const h of hunks) {
    if (h.kind === "equal") {
      out.push(...h.lines);
    } else {
      out.push(...acceptedChangeIndices.has(changeIdx) ? h.after : h.before);
      changeIdx++;
    }
  }
  return out.join(eol);
}

// src/settings.ts
var DEFAULT_BACKEND_URL = "http://127.0.0.1:8000";
var RwsSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Журнал").setDesc(
      "Профиль журнала задаёт правило первого упоминания (IAST) и проверку объёма, аннотации и ключевых слов. «Без журнала» отключает проверку соответствия."
    ).addDropdown((dropdown) => {
      var _a;
      dropdown.addOption("none", "— без журнала —");
      for (const [id, profile] of Object.entries(JOURNALS)) {
        dropdown.addOption(id, (_a = profile == null ? void 0 : profile.name) != null ? _a : id);
      }
      dropdown.setValue(this.plugin.settings.journal);
      dropdown.onChange(async (value) => {
        this.plugin.settings.journal = value;
        await this.plugin.saveSettings();
        this.plugin.relintAll();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Проверки транслитерации").setHeading();
    for (const type of FINDING_TYPES) {
      new import_obsidian.Setting(containerEl).setName(FINDING_TYPE_LABELS[type]).addToggle((toggle) => {
        toggle.setValue(this.plugin.settings.checks[type] !== false);
        toggle.onChange(async (value) => {
          this.plugin.settings.checks[type] = value;
          await this.plugin.saveSettings();
          this.plugin.relintAll();
        });
      });
    }
    new import_obsidian.Setting(containerEl).setName("Совет (полный аудит, Tier 2)").setHeading();
    containerEl.createEl("p", {
      cls: "setting-item-description",
      text: "Команда «Full council audit» отправляет текст заметки локальному движку (rws web), который прогоняет мультиагентный Совет через выбранного провайдера. Движок должен быть запущен; правка сохраняется в соседнюю заметку."
    });
    new import_obsidian.Setting(containerEl).setName("Адрес движка").setDesc("URL локального API RuWritingStyles.").addText((text) => {
      text.setPlaceholder(DEFAULT_BACKEND_URL);
      text.setValue(this.plugin.settings.backendUrl);
      text.onChange(async (value) => {
        const trimmed = value.trim();
        if (trimmed && !isValidBackendUrl(trimmed)) {
          new import_obsidian.Notice("RuWritingStyles: адрес движка должен начинаться с http:// или https://");
          this.plugin.settings.backendUrl = DEFAULT_BACKEND_URL;
        } else {
          this.plugin.settings.backendUrl = trimmed || DEFAULT_BACKEND_URL;
        }
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Токен API").setDesc("Только если движок запущен с RWS_API_TOKEN. Иначе оставьте пустым.").addText((text) => {
      text.inputEl.type = "password";
      text.setValue(this.plugin.settings.apiToken);
      text.onChange(async (value) => {
        this.plugin.settings.apiToken = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Провайдер").setDesc("LLM-провайдер для Совета (по умолчанию DeepSeek).").addDropdown((dropdown) => {
      for (const id of ["deepseek", "openai", "google", "anthropic", "openrouter", "local", "ollama", "mock"]) {
        dropdown.addOption(id, id);
      }
      dropdown.setValue(this.plugin.settings.auditProvider);
      dropdown.onChange(async (value) => {
        this.plugin.settings.auditProvider = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Профиль").setDesc("Профиль пользователя для прогона.").addDropdown((dropdown) => {
      for (const id of ["researcher", "editor", "student"]) {
        dropdown.addOption(id, id);
      }
      dropdown.setValue(this.plugin.settings.auditProfile);
      dropdown.onChange(async (value) => {
        this.plugin.settings.auditProfile = value;
        await this.plugin.saveSettings();
      });
    });
  }
};

// src/tier2/audit.ts
var import_obsidian2 = require("obsidian");
var auditInProgress = false;
var sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
function errorText(e) {
  return e instanceof Error ? e.message : String(e);
}
function readJson(resp) {
  try {
    return resp.json;
  } catch (e) {
    throw new Error("non-JSON response body");
  }
}
async function postExecute(s, text, filename) {
  const resp = await (0, import_obsidian2.requestUrl)({
    url: `${baseUrl(s)}/runs/execute`,
    method: "POST",
    headers: auditHeaders(s),
    body: JSON.stringify(executeBody(text, filename, s)),
    throw: false
  });
  if (resp.status !== 200) {
    throw new Error(`HTTP ${resp.status}${resp.text ? ` — ${resp.text}` : ""}`);
  }
  return validateExecuteResponse(readJson(resp)).run_id;
}
async function getRun(s, runId) {
  const resp = await (0, import_obsidian2.requestUrl)({
    url: `${baseUrl(s)}/runs/${runId}`,
    method: "GET",
    headers: auditHeaders(s),
    throw: false
  });
  switch (classifyHttpStatus(resp.status)) {
    case "not_found":
      throw new RunNotFoundError(`run ${runId} not found`);
    case "client_config":
      throw new ClientConfigError(`HTTP ${resp.status}`);
    case "transient":
      throw new TransientError(`HTTP ${resp.status}`);
    default:
      try {
        return validateRunDetails(readJson(resp));
      } catch (e) {
        throw new ClientConfigError(errorText(e));
      }
  }
}
function abortMessage(reason, runId, base) {
  switch (reason) {
    case "not_found":
      return `RuWritingStyles: прогон ${runId} не найден на движке (${base}).`;
    case "client_config":
      return `RuWritingStyles: ошибка конфигурации движка (HTTP 4xx). Проверьте адрес и токен.`;
    case "transient_exhausted":
      return `RuWritingStyles: движок недоступен (несколько ошибок подряд). Запущен ли rws web на ${base}?`;
    case "timeout":
      return `RuWritingStyles: Совет (${runId}) не завершился за отведённое время.`;
    default:
      return `RuWritingStyles: Совет (${runId}) — ${reason}.`;
  }
}
function openTrace(settings, runId, onLine) {
  let socket = null;
  try {
    socket = new WebSocket(wsUrl(settings, runId));
    socket.onmessage = (ev) => {
      if (typeof ev.data !== "string") return;
      try {
        const line = formatTraceMessage(JSON.parse(ev.data));
        if (line) onLine(line);
      } catch (e) {
      }
    };
    socket.onerror = () => {
      console.warn("RuWritingStyles: live trace WebSocket unavailable; polling continues.");
    };
  } catch (e) {
    socket = null;
  }
  return () => {
    try {
      socket == null ? void 0 : socket.close();
    } catch (e) {
    }
  };
}
async function runCouncilAudit(app, file, text, settings) {
  var _a, _b;
  if (!text.trim()) {
    new import_obsidian2.Notice("RuWritingStyles: пустая заметка — нечего отправлять Совету.");
    return;
  }
  if (!isValidBackendUrl(settings.backendUrl)) {
    new import_obsidian2.Notice(
      "RuWritingStyles: неверный адрес движка в настройках — нужен http:// или https://.",
      1e4
    );
    return;
  }
  if (auditInProgress) {
    new import_obsidian2.Notice("RuWritingStyles: аудит уже выполняется — дождитесь завершения.");
    return;
  }
  auditInProgress = true;
  const base = baseUrl(settings);
  const filename = (_a = file == null ? void 0 : file.basename) != null ? _a : "obsidian-note";
  const progress = new import_obsidian2.Notice("RuWritingStyles: запуск Совета…", 0);
  let closeTrace = () => {
  };
  try {
    let runId;
    try {
      runId = await postExecute(settings, text, filename);
    } catch (e) {
      if (e instanceof ClientConfigError) {
        new import_obsidian2.Notice(`RuWritingStyles: ошибка настроек — ${errorText(e)}.`, 12e3);
      } else {
        new import_obsidian2.Notice(
          `RuWritingStyles: не удалось запустить Совет — ${errorText(e)}. Запущен ли движок (rws web) на ${base}?`,
          12e3
        );
      }
      return;
    }
    progress.setMessage(`RuWritingStyles: Совет запущен (${runId})…`);
    closeTrace = openTrace(
      settings,
      runId,
      (line) => progress.setMessage(`RuWritingStyles: ${runId} — ${line}`)
    );
    let details = null;
    let abortReason = "timeout";
    let consecutiveFailures = 0;
    let lastStatus;
    for (let attempt = 1; attempt <= MAX_POLL_ATTEMPTS; attempt++) {
      let status;
      let current = null;
      let fatal;
      try {
        current = await getRun(settings, runId);
        status = current.status;
        consecutiveFailures = 0;
      } catch (e) {
        if (e instanceof RunNotFoundError) fatal = "not_found";
        else if (e instanceof ClientConfigError) fatal = "client_config";
        else consecutiveFailures++;
      }
      const decision = shouldAbortPolling({ status, attempt, consecutiveFailures, fatal });
      if (decision.abort) {
        abortReason = (_b = decision.reason) != null ? _b : "timeout";
        if (abortReason === "completed") details = current;
        break;
      }
      if (status && status !== lastStatus) {
        lastStatus = status;
        progress.setMessage(`RuWritingStyles: Совет (${runId}) — ${status}`);
      }
      if (attempt < MAX_POLL_ATTEMPTS) await sleep(POLL_INTERVAL_MS);
    }
    closeTrace();
    progress.hide();
    if (!details) {
      new import_obsidian2.Notice(abortMessage(abortReason, runId, base), 12e3);
      return;
    }
    if (details.status === "failed") {
      new import_obsidian2.Notice(`RuWritingStyles: прогон ${runId} завершился ошибкой — см. логи движка.`, 12e3);
      return;
    }
    await presentResult(app, file, details, details.status === "needs_human_review");
  } finally {
    closeTrace();
    progress.hide();
    auditInProgress = false;
  }
}
function presentResult(app, file, details, needsReview) {
  var _a;
  const revised = (_a = details.revised_text) != null ? _a : "";
  if (!revised.trim()) {
    new import_obsidian2.Notice(`RuWritingStyles: ${summarizeRun(details)}. Правка не получена.`, 12e3);
    return Promise.resolve();
  }
  return new Promise((resolve) => {
    new AuditResultModal(app, file, details, needsReview, resolve).open();
  });
}
async function applyToNote(app, file, revised, details) {
  if (!file) {
    await writeSiblingNote(app, file, revised, details);
    return;
  }
  try {
    await app.vault.modify(file, revised);
    new import_obsidian2.Notice("RuWritingStyles: правка применена к заметке (Ctrl+Z для отмены).", 8e3);
  } catch (e) {
    new import_obsidian2.Notice(`RuWritingStyles: не удалось применить правку — ${errorText(e)}`, 12e3);
  }
}
async function writeSiblingNote(app, file, revised, details) {
  var _a, _b;
  const folder = (file == null ? void 0 : file.parent) && file.parent.path !== "/" ? `${file.parent.path}/` : "";
  const stem = (_a = file == null ? void 0 : file.basename) != null ? _a : "obsidian-note";
  let target = `${folder}${stem}.rws-revised.md`;
  if (app.vault.getAbstractFileByPath(target)) {
    target = `${folder}${stem}.rws-revised.${sanitizeRunId((_b = details.id) != null ? _b : "run")}.md`;
  }
  try {
    const created = await app.vault.create(target, revised);
    await app.workspace.getLeaf(true).openFile(created);
    new import_obsidian2.Notice(`RuWritingStyles: правка → ${target}`, 8e3);
  } catch (e) {
    new import_obsidian2.Notice(`RuWritingStyles: не удалось записать правку — ${errorText(e)}`, 12e3);
  }
}
var MAX_RENDERED_HUNKS = 200;
var AuditResultModal = class extends import_obsidian2.Modal {
  constructor(app, file, details, needsReview, onResolve) {
    var _a, _b;
    super(app);
    this.file = file;
    this.details = details;
    this.needsReview = needsReview;
    this.onResolve = onResolve;
    this.resolved = false;
    this.original = (_a = details.original_text) != null ? _a : "";
    this.revised = (_b = details.revised_text) != null ? _b : "";
    this.eol = detectEol(this.original);
    this.wholeOnly = this.original.trim() === "";
    this.hunks = diffLines(this.original, this.revised);
    this.accepted = new Array(countChangeHunks(this.hunks)).fill(true);
  }
  onOpen() {
    var _a;
    const { contentEl } = this;
    contentEl.createEl("h3", { text: "RuWritingStyles — результат Совета" });
    contentEl.createEl("p", { text: summarizeRun(this.details) });
    if (this.needsReview) {
      contentEl.createEl("p", {
        cls: "mod-warning",
        text: "Статус: нужна экспертная проверка — правка получена, но верификатор не дал полного подтверждения."
      });
    }
    const warnings = (_a = this.details.verification) == null ? void 0 : _a.warnings;
    if (Array.isArray(warnings) && warnings.length) {
      const det = contentEl.createEl("details");
      det.createEl("summary", { text: `Предупреждения верификатора (${warnings.length})` });
      const list = det.createEl("ul");
      for (const w of warnings.slice(0, 50)) {
        const message = w && typeof w === "object" && "message" in w ? String(w.message) : String(w);
        list.createEl("li", { text: message });
      }
    }
    const revised = this.revised;
    const changeCount = this.accepted.length;
    if (this.wholeOnly) {
      contentEl.createEl("p", {
        text: "Оригинальный текст не получен от движка — доступно применение правки целиком."
      });
      new import_obsidian2.Setting(contentEl).addButton(
        (btn) => btn.setButtonText("Применить к заметке (полностью)").setCta().onClick(async () => {
          this.close();
          await applyToNote(this.app, this.file, revised, this.details);
        })
      ).addButton(
        (btn) => btn.setButtonText("В отдельную заметку").onClick(async () => {
          this.close();
          await writeSiblingNote(this.app, this.file, revised, this.details);
        })
      ).addButton((btn) => btn.setButtonText("Отмена").onClick(() => this.close()));
      return;
    }
    if (changeCount === 0) {
      contentEl.createEl("p", { text: "Изменений нет — правка совпадает с заметкой." });
      new import_obsidian2.Setting(contentEl).addButton(
        (btn) => btn.setButtonText("Закрыть").setCta().onClick(() => this.close())
      );
      return;
    }
    contentEl.createEl("p", {
      cls: "setting-item-description",
      text: "Отметьте изменения для применения; снятые останутся как в оригинале. «Применить выбранные» меняет текущую заметку (Ctrl+Z для отмены)."
    });
    this.renderHunks(contentEl);
    new import_obsidian2.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Применить выбранные").setCta().onClick(async () => {
        const set = /* @__PURE__ */ new Set();
        this.accepted.forEach((on, i) => {
          if (on) set.add(i);
        });
        this.close();
        await applyToNote(this.app, this.file, reconstruct(this.hunks, set, this.eol), this.details);
      })
    ).addButton(
      (btn) => btn.setButtonText("В отдельную заметку (полностью)").onClick(async () => {
        this.close();
        await writeSiblingNote(this.app, this.file, revised, this.details);
      })
    ).addButton((btn) => btn.setButtonText("Отмена").onClick(() => this.close()));
  }
  /** Render each change hunk with an accept toggle and a capped before/after. */
  renderHunks(container) {
    const list = container.createEl("div", { cls: "rws-diff-list" });
    let changeIdx = 0;
    let rendered = 0;
    for (const hunk of this.hunks) {
      if (hunk.kind !== "change") continue;
      const idx = changeIdx++;
      if (rendered >= MAX_RENDERED_HUNKS) continue;
      rendered++;
      const row = list.createEl("div", { cls: "rws-diff-hunk" });
      new import_obsidian2.Setting(row).setName(`Изменение ${idx + 1}`).addToggle((toggle) => {
        toggle.setValue(true);
        toggle.onChange((value) => {
          this.accepted[idx] = value;
        });
      });
      const pre = row.createEl("pre", { cls: "rws-diff-pre" });
      for (const line of hunk.before.slice(0, 8)) {
        pre.createEl("div", { cls: "rws-diff-del", text: `− ${line}` });
      }
      for (const line of hunk.after.slice(0, 8)) {
        pre.createEl("div", { cls: "rws-diff-add", text: `+ ${line}` });
      }
      if (hunk.before.length > 8 || hunk.after.length > 8) {
        pre.createEl("div", { text: "…" });
      }
    }
    if (changeIdx > MAX_RENDERED_HUNKS) {
      container.createEl("p", {
        cls: "setting-item-description",
        text: `Показаны первые ${MAX_RENDERED_HUNKS} из ${changeIdx} изменений; остальные применяются по умолчанию.`
      });
    }
  }
  onClose() {
    this.contentEl.empty();
    if (!this.resolved) {
      this.resolved = true;
      this.onResolve();
    }
  }
};

// src/ui/lint-extension.ts
var import_view = require("@codemirror/view");
var import_lint = require("@codemirror/lint");

// src/lint/quickfix.ts
function iastInsertion(finding2, terms) {
  if (finding2.type !== "missing_iast_on_first_mention" || !finding2.term) return null;
  const term = terms.find((t) => t.ru === finding2.term);
  if (!term || !term.iast) return null;
  return ` (${term.iast})`;
}

// src/ui/lint-extension.ts
var RWS_SOURCE = "RuWritingStyles";
function isEnabled(checks, type) {
  return checks[type] !== false;
}
function countRwsDiagnostics(diagnostics) {
  let errors = 0;
  let warnings = 0;
  for (const d of diagnostics) {
    if (d.source !== RWS_SOURCE) continue;
    if (d.severity === "error") errors++;
    else if (d.severity === "warning") warnings++;
  }
  return { errors, warnings };
}
function makeRwsLintExtension(host) {
  const lintSource = (view) => {
    const { terms, journal, enabledChecks } = host.getLintConfig();
    const text = view.state.doc.toString();
    const result = lintText(text, terms, journal);
    const located = locateFindings(text, result.findings, terms);
    const diagnostics = [];
    for (const f of located) {
      if (!isEnabled(enabledChecks, f.type)) continue;
      if (f.from == null || f.to == null || f.to <= f.from) continue;
      const diagnostic = {
        from: f.from,
        to: f.to,
        severity: f.severity === "error" ? "error" : "warning",
        message: f.message,
        source: RWS_SOURCE
      };
      const insertion = iastInsertion(f, terms);
      if (insertion) {
        diagnostic.actions = [
          {
            name: "Вставить IAST",
            apply: (editorView, _from, to) => {
              editorView.dispatch({ changes: { from: to, insert: insertion } });
            }
          }
        ];
      }
      diagnostics.push(diagnostic);
    }
    if (text.length > 0) {
      const compliance = checkJournal(text, journal);
      if (compliance) {
        const newline = text.indexOf("\n");
        const end = newline > 0 ? newline : text.length;
        for (const gap of journalGaps(compliance)) {
          diagnostics.push({
            from: 0,
            to: end,
            severity: gap.severity === "error" ? "error" : "warning",
            message: gap.message,
            source: RWS_SOURCE
          });
        }
      }
    }
    return diagnostics;
  };
  const statusSync = import_view.EditorView.updateListener.of((update) => {
    if (!update.view.hasFocus) return;
    const collected = [];
    (0, import_lint.forEachDiagnostic)(update.state, (d) => collected.push(d));
    const { errors, warnings } = countRwsDiagnostics(collected);
    host.reportCounts(errors, warnings);
  });
  return [(0, import_lint.linter)(lintSource, { delay: 400 }), import_view.keymap.of(import_lint.lintKeymap), statusSync];
}

// src/main.ts
function allChecksEnabled() {
  return Object.fromEntries(FINDING_TYPES.map((t) => [t, true]));
}
var DEFAULT_SETTINGS = {
  journal: "none",
  checks: allChecksEnabled(),
  backendUrl: "http://127.0.0.1:8000",
  apiToken: "",
  auditProvider: "deepseek",
  auditProfile: "researcher"
};
var RuWritingStylesPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.terms = TERMS;
    this.statusBar = null;
  }
  async onload() {
    await this.loadSettings();
    this.statusBar = this.addStatusBarItem();
    this.statusBar.addClass("rws-statusbar");
    this.registerEditorExtension(
      makeRwsLintExtension({
        getLintConfig: () => ({
          terms: this.terms,
          journal: this.currentJournal(),
          enabledChecks: this.settings.checks
        }),
        reportCounts: (errors, warnings) => this.setStatus(errors, warnings)
      })
    );
    this.addSettingTab(new RwsSettingTab(this.app, this));
    this.addCommand({
      id: "lint-current-note",
      name: "Lint current note (show problems)",
      editorCallback: (editor, _ctx) => this.showProblems(editor)
    });
    this.addCommand({
      id: "council-audit",
      name: "Full council audit (run on engine)",
      editorCallback: (editor, ctx) => {
        var _a;
        const file = ctx instanceof import_obsidian3.MarkdownView ? ctx.file : (_a = ctx.file) != null ? _a : null;
        void runCouncilAudit(this.app, file, editor.getValue(), this.auditSettings());
      }
    });
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", () => this.refreshStatus())
    );
    this.refreshStatus();
  }
  onunload() {
  }
  /** Resolve the active journal profile (or null for "none"). */
  currentJournal() {
    var _a;
    return (_a = JOURNALS[this.settings.journal]) != null ? _a : null;
  }
  /** The Tier-2 engine connection settings (incl. the selected journal). */
  auditSettings() {
    return {
      backendUrl: this.settings.backendUrl,
      apiToken: this.settings.apiToken,
      provider: this.settings.auditProvider,
      profile: this.settings.auditProfile,
      journal: this.settings.journal
    };
  }
  /** Obsidian's Editor wraps a CM6 EditorView, exposed (untyped) as `.cm`. */
  cmOf(editor) {
    var _a;
    return (_a = editor.cm) != null ? _a : null;
  }
  showProblems(editor) {
    const cm = this.cmOf(editor);
    if (cm) {
      (0, import_lint2.forceLinting)(cm);
      (0, import_lint2.openLintPanel)(cm);
    }
    const text = editor.getValue();
    const profile = this.currentJournal();
    const findings = lintText(text, this.terms, profile).findings.filter(
      (f) => this.settings.checks[f.type] !== false
    );
    const lines = [];
    if (findings.length === 0) {
      lines.push("транслитерация — замечаний нет");
    } else {
      const located = locateFindings(text, findings, this.terms).filter(
        (f) => f.from != null && f.to != null
      ).length;
      lines.push(`транслитерация — ${findings.length} замечани${plural(findings.length)}`);
      if (located < findings.length) {
        lines.push(`${findings.length - located} без точной привязки (не показаны в тексте)`);
      }
    }
    const compliance = checkJournal(text, profile);
    if (compliance) lines.push(summarizeJournal(compliance));
    new import_obsidian3.Notice("RuWritingStyles: " + lines.join(" · "), 12e3);
  }
  /** Re-lint every open markdown editor (after a settings change). */
  relintAll() {
    for (const leaf of this.app.workspace.getLeavesOfType("markdown")) {
      const cm = this.cmOf(leaf.view.editor);
      if (cm) (0, import_lint2.forceLinting)(cm);
    }
    this.refreshStatus();
  }
  setStatus(errors, warnings) {
    if (!this.statusBar) return;
    this.statusBar.setText(
      errors === 0 && warnings === 0 ? "RWS ✓" : `RWS ✗${errors} ⚠${warnings}`
    );
  }
  /** Recount from the active note's editor (covers leaf switches). */
  refreshStatus() {
    var _a;
    const view = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
    const cm = view ? this.cmOf(view.editor) : null;
    if (!cm) {
      (_a = this.statusBar) == null ? void 0 : _a.setText("");
      return;
    }
    const collected = [];
    (0, import_lint2.forEachDiagnostic)(cm.state, (d) => {
      if (d.source === RWS_SOURCE) collected.push(d);
    });
    const { errors, warnings } = countRwsDiagnostics(collected);
    this.setStatus(errors, warnings);
  }
  async loadSettings() {
    const data = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, data);
    this.settings.checks = Object.assign(allChecksEnabled(), data == null ? void 0 : data.checks);
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
function plural(n) {
  const d = n % 10;
  const dd = n % 100;
  if (d === 1 && dd !== 11) return "е";
  if (d >= 2 && d <= 4 && (dd < 12 || dd > 14)) return "я";
  return "й";
}
